force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>EPC code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Destination</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventory (Shipping Destination)</relationshipLabel>
    <relationshipName>Inventory1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shipping_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Date_Time__c</fullName>
    <label>Shipping Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipped By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>User</label>
</CustomObject>

force-app/main/default/classes/shippingcomponent.cls
public class shippingcomponent 
{
    public string EPC{set;get;}
    public string location{set;get;}
    public list<selectoption> lstoptionlocation{get;set;}
    list<location__c> loc = new list<location__c>();
 
    public shippingcomponent ()
    {
        String message = '' + ApexPages.CurrentPage().GetParameters().Get('message');
        String pageHeaderReferer = ApexPages.currentPage().getHeaders().get('Referer'); 

        if(pageHeaderReferer != null && pageHeaderReferer.containsIgnoreCase('shipping') && message != 'null')
        {
               ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, message)); 
        }
        lstoptionlocation=new list<selectoption>();
        list<Location__c> locations=[select id,name from Location__c];
        lstoptionlocation.add(new selectoption('--None--','--None--'));
        for(Location__c l:locations)
        {
            lstoptionlocation.add(new selectoption(l.id,l.name));
        }
    }
    public pagereference ship()
    {
        pagereference pg;
        if(EPC==null || EPC=='')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'EPC is required. ')); 
        }
        else
        {
            list<inventory__c> inven = [select id,name, EPC__c from inventory__c where epc__c=:EPC];
            loc =[select id,name from location__c where name=:location];
            if(!inven.isEmpty())
            {
                if(location == '--None--' || location ==null  )
                {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Location is required. '));
                    return null;
                    
                }
                else
                {
                    inven[0].Shipping__c= location; 
                }
                inven[0].user__c=userinfo.getuserId() ;
                inven[0].Shipping_Date_Time__c=DateTime.now();
                update inven;
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'EPC doesnot match. ')); 
            }
          //  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Product Shipped Successfully '));
            pg=new pagereference('/apex/CustomTab?SelectedTab=Shipping');
           // pg.getParameters().put('message', 'Product Shipped Successfully');
            pg.setRedirect(true); 
        }    
        return pg;
    }     
}