force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>EPC code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Destination</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventory (Shipping Destination)</relationshipLabel>
    <relationshipName>Inventory1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shipping_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Date_Time__c</fullName>
    <label>Shipping Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipped By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/location_ID__c.field-meta.xml
<CustomField>
    <fullName>location_ID__c</fullName>
    <label>location ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>User</label>
</CustomObject>

force-app/main/default/classes/shipping.cls
public class shipping 
{
    public string EPC{set;get;}
    public string location{set;get;}
    public integer locid{get;set;}
    public list<selectoption> lstoptionlocation{get;set;}
    public list<location__c> loc;
    public string strError{get;set;}
    public shipping()
    {
        String message = '' + ApexPages.CurrentPage().GetParameters().Get('message');
        String pageHeaderReferer = ApexPages.currentPage().getHeaders().get('Referer'); 

        if(pageHeaderReferer != null && pageHeaderReferer.containsIgnoreCase('shipping') && message != 'null')
        {
               ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, message)); 
        }   
        lstoptionlocation=new list<selectoption>();
        loc=new list<location__c>();
        list<Location__c> locations=[select id,name from Location__c];
        lstoptionlocation.add(new selectoption('','--None--'));
        for(Location__c l:locations)
        {
            lstoptionlocation.add(new selectoption(l.id,l.name));
        }
    }
    public pagereference ship()
    {
        system.debug('-----------epc------'+EPC);
        list<inventory__c> inven = [select id,name, EPC__c from inventory__c where epc__c=:EPC];
        loc =[select id,name,location_ID__c from location__c where location_ID__c=:locid];
        system.debug('---------inven-------'+inven);
        if(!inven.isEmpty())
        {
            if(string.isNotBlank(location) && location != '')
            {
                inven[0].Shipping__c= location;
            }
            else if(!loc.isEmpty())
            {
                inven[0].Shipping__c= loc[0].id;
            }
            inven[0].user__c=userinfo.getuserId() ;
            inven[0].Shipping_Date_Time__c=DateTime.now();
            update inven;
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'EPC doesnot match. ')); 
        }
     
     pagereference pg=new pagereference('/apex/shipping');  
            
        pg.getParameters().put('message', 'Product Shipped Successfully');
         pg.setRedirect(true);
       
        return pg;
           
    }     
}