force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>EPC code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/LocationID__c.field-meta.xml
<CustomField>
    <fullName>LocationID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>LocationID</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/LOT__c.field-meta.xml
<CustomField>
    <fullName>LOT__c</fullName>
    <label>LOT</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_number__c.field-meta.xml
<CustomField>
    <fullName>Product_number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product number</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/location_ID__c.field-meta.xml
<CustomField>
    <fullName>location_ID__c</fullName>
    <label>location ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>product number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <label>GTIN</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/scan__c/scan__c.object-meta.xml
<CustomObject>
    <label>scan</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/scan__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EPC</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>scans</relationshipLabel>
    <relationshipName>scans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/scan__c/fields/LocationID__c.field-meta.xml
<CustomField>
    <fullName>LocationID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>LocationID</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>scans</relationshipLabel>
    <relationshipName>scans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/scan__c/fields/Scan_time__c.field-meta.xml
<CustomField>
    <fullName>Scan_time__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Scan time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TotalHistotyReportControllerTest.cls
@isTest
public class TotalHistotyReportControllerTest
{
    public static testmethod void report()
    {
        Location__c location=new Location__c(name='chicago',location_ID__c=10);
        insert location;
        Product__c product=new Product__c(GTIN__c='Test gtin',Product_Description__c='Test description');
        insert product;
        
        Inventory__c inventory =new Inventory__c(LocationID__c=location.id,Product_number__c=product.id,LOT__c='Mac123');
        insert inventory;
        
        scan__c scan=new scan__c(EPC__c=inventory.id,LocationID__c=location.id,Scan_time__c=system.now());
        insert scan;
        
        
        apexpages.currentpage().getparameters().put('sd','12/29/2016');
        apexpages.currentpage().getparameters().put('ed','12/31/2016');
     //   apexpages.currentpage().getparameters().put('lo','location.id');
        TotalHistotyReportController totalreport=new TotalHistotyReportController();
        totalreport.fetchDetails();
        
    }
}