force-app/main/default/objects/inven__c/inven__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Product Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/inven__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/Expiry__c.field-meta.xml
<CustomField>
    <fullName>Expiry__c</fullName>
    <label>Expiry</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/UPN__c.field-meta.xml
<CustomField>
    <fullName>UPN__c</fullName>
    <label>UPN</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/Sca__c.object-meta.xml
<CustomObject>
    <label>Scan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sca__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <formula>IF( OR( ISBLANK( Scanned__Latitude__s   ) , ISBLANK(  Scanned__Longitude__s  ) ) , &quot;Missing Coordinates&quot;, IMAGE( Map_Link__c , &quot;&quot;, 350,400))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Map</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/fields/Map_Link__c.field-meta.xml
<CustomField>
    <fullName>Map_Link__c</fullName>
    <formula>&quot;https://maps.googleapis.com/maps/api/staticmap?center=&quot; &amp; TEXT( Scanned__Latitude__s ) &amp; &quot;,&quot; &amp; TEXT( Scanned__Longitude__s ) &amp; &quot;&amp;zoom=6&amp;size=400x350&amp;sensor=true&amp;markers=color:red%7Clabel:A%7C&quot;&amp; TEXT( Scanned__Latitude__s ) &amp; &quot;,&quot; &amp; TEXT( Scanned__Longitude__s )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Map Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/fields/Scanned_Date__c.field-meta.xml
<CustomField>
    <fullName>Scanned_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Scanned Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ListOfScans.cls
public class ListOfScans 
{
    public list<wrapper> lstwrapper{get;set;}
    public integer rowIndex{get;set;}
    public list<sca__c> lstscan{get;set;}
    public ListOfScans()
    {
        map<string, wrapper> mapReport = new  map<string, wrapper>();
        lstwrapper =new list<wrapper>();
        Map<String,Inven__c > InvMap = new Map<String,Inven__c >();
        List<Inven__c> inven=[SELECT ID,Name,EPC__c, UPN__c, Lot__c,Expiry__c from Inven__c where EPC__c!=null];
        for(Inven__c inv:inven){
            InvMap.put(inv.EPC__c,inv);
        }
        List<Sca__c> scan= [SELECT EPC__c,Scanned__Latitude__s,Scanned__Longitude__s, Scanned_Date__c,Map_Link__c from Sca__c where EPC__c!=null];
        Map<String,Sca__c > scanMap = new Map<String,Sca__c >();        
        for(Sca__c sc:scan){
            if(!scanMap.containskey(sc.epc__c))
            scanMap.put(sc.epc__C,sc);
            else if(scanMap.containskey(sc.epc__c) && sc.Scanned_Date__c > scanMap.get(sc.epc__c).Scanned_Date__c ){
            scanMap.put(sc.epc__C,sc);   
            }
        }
        for(integer i=0; i<scanMap.values().size();i++)
        {
        
          //  if(InvMap.containskey(scan[i].EPC__c))
            {
            wrapper objWrap = new wrapper();
            objwrap.epc = scanMap.values()[i].EPC__c;
            objwrap.Scanneddate= scanMap.values()[i].Scanned_Date__c ;
            objwrap.scannedLatitude= scanMap.values()[i].Scanned__Latitude__s;
            objwrap.scannedLongitude= scanMap.values()[i].Scanned__Longitude__s;           
            objwrap.name= (InvMap.containskey(scanMap.values()[i].EPC__c)?InvMap.get(scanMap.values()[i].EPC__c).name:'');
            objwrap.upn= (InvMap.containskey(scanMap.values()[i].EPC__c)?InvMap.get(scanMap.values()[i].EPC__c).UPN__c:'');
            objwrap.expiry= (InvMap.containskey(scanMap.values()[i].EPC__c)?InvMap.get(scanMap.values()[i].EPC__c).Expiry__c:null);
            objwrap.lot= (InvMap.containskey(scanMap.values()[i].EPC__c)?InvMap.get(scanMap.values()[i].EPC__c).Lot__c:'');
            objwrap.gmap = scanMap.values()[i].Map_Link__c ;
            lstwrapper.add(objwrap);
            }
        }
    }
    public boolean displayPopup {get; set;}    
   
    public void closePopup()
    {       
        displayPopup = false;   
    }    
    public void showPopup()
    {       
        lstscan=[select id,name,map__c from sca__c where Map_Link__c =:lstwrapper[rowIndex].gmap];
        displayPopup = true;   
    }   
    
    
    public class wrapper
    {
        public string name{get;set;}  
        public string epc{get;set;}  
        public string upn{get;set;}  
        public date expiry{get;set;}
        public string lot{get;set;}  
        public datetime Scanneddate{get;set;}  
        public Decimal scannedLatitude{get;set;}  
        public Decimal scannedLongitude{get;set;}
        public string gmap{get;set;}  
    }
}