force-app/main/default/objects/inven__c/inven__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Product Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/inven__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/Expiry__c.field-meta.xml
<CustomField>
    <fullName>Expiry__c</fullName>
    <label>Expiry</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inven__c/fields/UPN__c.field-meta.xml
<CustomField>
    <fullName>UPN__c</fullName>
    <label>UPN</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/Sca__c.object-meta.xml
<CustomObject>
    <label>Scan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sca__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sca__c/fields/Scanned_Date__c.field-meta.xml
<CustomField>
    <fullName>Scanned_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Scanned Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Var.cls
public class Var 
{

        public List<Sca__c> audited{get;set;}
        public List<Inven__c > missed{get;set;}
        public List<Sca__c> extra{get;set;}
        
    public Var()
    {
        missed=new List<Inven__c >();
        audited=new List<sca__c>();
        extra= new List<sca__c>();
    }
        
    public pagereference fetchDetails()
    {
        audited.clear();
        missed.clear();
        extra.clear();
          
        set<string> sepc=new set<string>();
        set<string> iepc=new set<string>();      

        date srdate = date.valueof(date.parse(Apexpages.currentPage().getParameters().get('sd')));
        date eddate = date.valueof(date.parse(Apexpages.currentPage().getParameters().get('ed')));       
        
        List<Sca__c> lstscan=[SELECT ID,EPC__c,Scanned_Date__c,Scanned__Latitude__s,Scanned__Longitude__s FROM Sca__c WHERE DAY_ONLY(createddate) >=:srdate and
                                   DAY_ONLY(createddate) <=:eddate];
                                  
        for(Sca__c s:lstscan)
        {
            sepc.add(s.EPC__c);
        }   
        
             
        List<Inven__c > linv=[SELECT ID,Name,EPC__c,Expiry__c,LOT__c,UPN__c, Createddate FROM Inven__c ];
        for(Inven__c i:linv)
        {
            iepc.add(i.EPC__c);
        }   
                        
        for (Sca__c scan:lstscan)
        {
           if(iepc.contains(scan.epc__c))   
           {
           audited.add(scan);          
           }
           else 
           {
           extra.add(scan);
           }       
        }
       
        for(Inven__c i: linv)
        {
            if(!sepc.contains(i.epc__c))
            {
                missed.add(i);
            }          
        }                
        return null;      
        }
}