force-app/main/default/objects/cyclecount__c/cyclecount__c.object-meta.xml
<CustomObject>
    <label>cyclecount</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cyclecounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cyclecount__c/fields/cycle_count_ID__c.field-meta.xml
<CustomField>
    <fullName>cycle_count_ID__c</fullName>
    <formula>Name &amp;&quot;&quot;&amp; Location__r.loc__c &amp;&quot;&quot;&amp;  text(CreatedDate)</formula>
    <label>cycle count ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cyclecount__c/fields/Pickl__c.field-meta.xml
<CustomField>
    <fullName>Pickl__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CyclecountUpdate.cls
@RestResource(urlMapping='/cyclecount/*')
global class CyclecountUpdate{

    @HttpPost 
    global static String cyclepost(String cid) 
    {
        cyclecount__c cyclecount=[select id,cycle_count_ID__c,Pickl__c from cyclecount__c where cycle_count_ID__c=:cid];
        if(cyclecount.cycle_count_ID__c !=null && cid==cyclecount.cycle_count_ID__c)
        {    
            cyclecount.Pickl__c='Close';
            update cyclecount; 
        }     
        return cyclecount.id;                        
    }
}