force-app/main/default/objects/cyclecount__c/cyclecount__c.object-meta.xml
<CustomObject>
    <label>cyclecount</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cyclecounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>EPC code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <label>EPC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/LocationID__c.field-meta.xml
<CustomField>
    <fullName>LocationID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>LocationID</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product_number__c.field-meta.xml
<CustomField>
    <fullName>Product_number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product number</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>product number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/scan__c/scan__c.object-meta.xml
<CustomObject>
    <label>scan</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/scan__c/fields/cyclecount__c.field-meta.xml
<CustomField>
    <fullName>cyclecount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>cyclecount</label>
    <referenceTo>cyclecount__c</referenceTo>
    <relationshipLabel>scans</relationshipLabel>
    <relationshipName>scans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/scan__c/fields/EPC__c.field-meta.xml
<CustomField>
    <fullName>EPC__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EPC</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>scans</relationshipLabel>
    <relationshipName>scans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/scan__c/fields/LocationID__c.field-meta.xml
<CustomField>
    <fullName>LocationID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>LocationID</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>scans</relationshipLabel>
    <relationshipName>scans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/scan__c/fields/Scan_time__c.field-meta.xml
<CustomField>
    <fullName>Scan_time__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Scan time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UnscanItemsPDFController.cls
public class UnscanItemsPDFController 
{
    public string cycleid{get;set;}
    public string locationid{get;set;}
    public list<Inventory__c> lstinventory{get;set;}
    public UnscanItemsPDFController()
    {
        lstinventory=new list<Inventory__c>();
        cycleid=Apexpages.currentpage().getparameters().get('cycle');
        locationid=Apexpages.currentpage().getparameters().get('location');
        
        map<id,scan__c> mapscan=new map<id,scan__c>();
        list<scan__c> lstscan=[select id,name,EPC__c,Scan_time__c from scan__c where cyclecount__c=:cycleid];
        for(scan__c s :lstscan)
        {
            mapscan.put(s.EPC__c,s);
        }
        
        list<Inventory__c> invntory=[select id,Name,EPC__c,Product_number__c,Product_number__r.name,Product_number__r.Product_Description__c,LocationID__c from Inventory__c where LocationID__c=:locationid];
        for(Inventory__c inv: invntory)
        {
            if(!mapscan.containsKey(inv.id))
            {
                lstinventory.add(inv);
            }
        }
        
    }
}