force-app/main/default/objects/cyclecount__c/cyclecount__c.object-meta.xml
<CustomObject>
    <label>cyclecount</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cyclecounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cyclecount__c/fields/cycle_count_ID__c.field-meta.xml
<CustomField>
    <fullName>cycle_count_ID__c</fullName>
    <formula>Name &amp;&quot;&quot;&amp; Location__r.loc__c &amp;&quot;&quot;&amp;  text(CreatedDate)</formula>
    <label>cycle count ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cyclecount__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>cycle_counts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cyclecount__c/fields/Pickl__c.field-meta.xml
<CustomField>
    <fullName>Pickl__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cyclecount__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Insertcyclecount.cls
@RestResource(urlMapping='/Restapiopencyclecount/*')
global class Insertcyclecount {

    @HttpPost
   
        global static String doPost(String name,String Location, date startdate) {
        cyclecount__c count = new cyclecount__c();
        count.Name = name;
        count.Location__c = Location;
        count.Start_date__c=startdate;
        count.Pickl__c='Open';
        insert count;
        return count.id;                                        //    string countid= count.id;
                                               //      countid = [SELECT Cycle_Count_ID__c FROM cyclecount__c where id =:countid];
                                                           
                                                    /*
                                                    {
                                        "name" : "123456789",
                                        "Location" : "a0541000000cXW0"
                                        }
                                        */         
}

}