force-app/main/default/objects/Assign_user__c/Assign_user__c.object-meta.xml
<CustomObject>
    <label>Assign user</label>
    <nameField>
        <label>Assign user Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_user__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Assign users</relationshipLabel>
    <relationshipName>Assign_users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_user__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Assign users</relationshipLabel>
    <relationshipName>Assign_users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assign_user__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Assign users</relationshipLabel>
    <relationshipName>Assign_users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/TerritoryID__c.field-meta.xml
<CustomField>
    <fullName>TerritoryID__c</fullName>
    <label>TerritoryID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>User</label>
</CustomObject>

force-app/main/default/classes/locationname.cls
@RestResource(urlMapping='/listlocation/*')
global with sharing class locationname
{
    @HttpGet
    global static list<Location__c> getlocations() 
    {
        set<string> lstempid =new set<string>();
        set<string> territorsid=new set<string>();
        set<string> locationassignid=new set<string>();
        list<Location__c> lstlocations=new list<Location__c>();
        list<Employee__c> lstemploy=[select id,name,User__c from Employee__c where User__c=:userinfo.getuserId()];
        for(Employee__c e: lstemploy)
        {
            lstempid.add(e.id); 
        }
        list<Assign_user__c> lstassignuser=[select id,name,Location__c,Employee__c,Territory__c from Assign_user__c where Employee__c IN :lstempid];
        for(Assign_user__c terr:lstassignuser)
        {
            locationassignid.add(terr.Location__c);
            territorsid.add(terr.Territory__c);
        }
        list<Territory__c> lstterritory=[select id,name,(select id,name from Locations__r)TerritoryID__c from Territory__c 
                                             where id IN:territorsid];
                                             
        list<Location__c> lstlocation=[select id,name from Location__c where id IN:locationassignid];
        for(Location__c loc:lstlocation)
        {
            lstlocations.add(loc);
        }
                                 
        for(Territory__c t:lstterritory) 
        {
            for(Location__c loc:t.Locations__r)
            {
               lstlocations.add(loc);
            }
        }        
        return lstlocations;
    } 
}